<a href="https://colab.research.google.com/github/VyshnaviPothamsetti/MachineLearning/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

In [3]:
data=pd.read_csv('/content/diabetes.csv')
data.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [7]:
x=data.drop('diabetes',axis=1).values
y=data['diabetes'].values
x.shape,y.shape

((768, 8), (768,))

In [9]:
y=y.reshape(-1,1)
y.shape

(768, 1)

In [102]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=30)

In [135]:
model=LogisticRegression(C=0.5)
model.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.5)

In [136]:
model.classes_,model.intercept_

(array([0, 1]), array([-8.14694081]))

In [137]:
model.predict_proba(x_test),x_test.shape,x_train.shape

(array([[0.89095495, 0.10904505],
        [0.85771874, 0.14228126],
        [0.8796813 , 0.1203187 ],
        [0.39611182, 0.60388818],
        [0.84854109, 0.15145891],
        [0.9512916 , 0.0487084 ],
        [0.29847605, 0.70152395],
        [0.74582546, 0.25417454],
        [0.65064183, 0.34935817],
        [0.95088105, 0.04911895],
        [0.89071183, 0.10928817],
        [0.82653341, 0.17346659],
        [0.89139386, 0.10860614],
        [0.8007298 , 0.1992702 ],
        [0.92862253, 0.07137747],
        [0.91635052, 0.08364948],
        [0.77051221, 0.22948779],
        [0.78975292, 0.21024708],
        [0.20864975, 0.79135025],
        [0.87271544, 0.12728456],
        [0.58770966, 0.41229034],
        [0.14263479, 0.85736521],
        [0.50824483, 0.49175517],
        [0.65354746, 0.34645254],
        [0.04007982, 0.95992018],
        [0.56416434, 0.43583566],
        [0.91356843, 0.08643157],
        [0.95689132, 0.04310868],
        [0.95518787, 0.04481213],
        [0.650

In [138]:
y_pred=model.predict(x_test)

In [139]:
model.score(x_test,y_test)

0.8181818181818182

In [140]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0])

In [141]:
confusion_matrix(y_test,y_pred)

array([[94, 10],
       [18, 32]])

In [142]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87       104
           1       0.76      0.64      0.70        50

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.81      0.82      0.81       154



###CONCLUSION
##As the value of logistic coefficient increases the score & accuracy of the model decreases 